spring.application.name=employee-api

spring.data.mongodb.uri=mongodb://mongodb:27017/employee_db
jwt.secret=VGhpc0lzTXlWZXJ5TG9uZ1NlY3JldEtleUZvckxlYXJuaW5nUHVycG9zZXNPbmx5MTIzNDU2Nzg5
jwt.expiration=86400000
